### ISSUE TITLE
NullPointer exception when using semiauto derived codecs

### ISSUE THREAD

**Issue by ostronom** [travisbrown/circe#326]
This code compiles and runs as expected:
```.scala
import cats.data.Xor
import io.circe.parser._
import io.circe._
import io.circe.generic.encoding.DerivedObjectEncoder
import io.circe.syntax._
import io.circe.generic.semiauto._
import io.circe.generic.auto._

case class O(i: Int)
sealed trait X
case class A(i: O) extends X
case class B(i: O) extends X

object Main extends App {
  def genEncoder[T: DerivedObjectEncoder](tag: String) = new Encoder[T] {
    val derived = deriveEncoder[T]
    override def apply(u: T) = derived(u).mapObject(o => o.add("$type", tag.asJson))
  }
  def genDecoder[T](discriminator: PartialFunction[String, Decoder[_ <: T]]) = new Decoder[T] {
    override def apply(c: HCursor) = c.downField("$type").as[String] match {
      case Xor.Right(tpe) if discriminator isDefinedAt tpe =>
        discriminator(tpe)(c)
      case _ => Xor.Left(DecodingFailure(s"Cannot deduce decoder", c.history))
    }
  }
  implicit val encoderA: Encoder[A] = genEncoder[A]("A")
  implicit val encoderB: Encoder[B] = genEncoder[B]("B")
  implicit val decoderA: Decoder[A] = deriveDecoder[A]
  implicit val decoderB: Decoder[B] = deriveDecoder[B]
  implicit val decoderC: Decoder[X] = genDecoder[X] {
    case "A" => decoderA
    case "B" => decoderB
  }

  val as = A(O(10)).asJson.noSpaces
  val bs = B(O(10)).asJson.noSpaces
  println(as, bs, parse(as).map(_.as[X]), parse(bs).map(_.as[X]))
}
```

But if I comment out `io.circe.generic.auto` import and provide 
```.scala
implicit val encoderO: Encoder[O] = deriveEncoder[O]
implicit val decoderO: DecoderO] = deriveDecoder[O]
```

the code still compiles, but throws NullPointer exception

```
at Main$$anon$1.encodeObject(stuff.scala:28)
        at Main$$anon$1.encodeObject(stuff.scala:28)
        at io.circe.generic.encoding.DerivedObjectEncoder$$anon$1.encodeObject(DerivedObjectEncoder.scala:18)
        at io.circe.ObjectEncoder$class.apply(ObjectEncoder.scala:12)
        at io.circe.generic.encoding.DerivedObjectEncoder.apply(DerivedObjectEncoder.scala:8)
        ...
```

**Comment by knutwalker** [comment]
I suspect you had the O En/Decoders written below the other ones? The implicit `DerivedObjectEncoder` for `genEncoder[A]` will use the definition of `encoderO`, even if it is defined later in the file. However, that also means that during the time of the initialization of `encoderA`, `encoderO` is still null as it itself has not yet been initialized. It's a weird scala thing, where order of initialization and implicit searches clash in ways you might not expect. It should work if you either 1) define the encoder/decoder for O above the ones for A/B, 2) make the A/B Encoders lazy vals or 3) make the O Encoder a lazy val.

**Comment by ostronom** [comment]
Yes, both three ways solve the problem. Thank you.
